/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ColorBotleGame } from "./ColorBotleGame";
export type { ERC20Token } from "./ERC20Token";
export type { MyAirdrop } from "./MyAirdrop";
