/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ColorBotleGame__factory } from "./ColorBotleGame__factory";
export { ERC20Token__factory } from "./ERC20Token__factory";
export { MyAirdrop__factory } from "./MyAirdrop__factory";
